name: PR Agent (Reusable)

on:
  workflow_call:
    secrets:
      ANTHROPIC_API_KEY:
        required: true

jobs:
  pr-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Claude Code
        run: npm install -g @anthropic-ai/claude-code

      - name: Configure Git
        run: |
          git config user.name "Claude Agent"
          git config user.email "claude-agent@users.noreply.github.com"

      - name: Run Agent
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr diff ${{ github.event.pull_request.number }} > diff.txt
          
          claude --print "
          Review this PR and fix any issues you find.
          
          $(cat diff.txt | head -500)
          
          If you make changes, commit them with a clear message.
          If no changes needed, say so.
          "

      - name: Push fixes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -m "fix: automated improvements from PR agent"
            git push
          fi
